# Generated by Django 3.0 on 2020-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200610_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='None', max_length=190),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='None', max_length=26),
        ),
    ]
